# Generated by Django 4.1.1 on 2022-11-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_mywatchlistitem_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlistitem',
            name='release_date',
            field=models.DateField(),
        ),
    ]
